apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deploy
  labels:
    app: user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user
  strategy: 
    type: RollingUpdate
    rollingUpdate:
     maxUnavailable: 2
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: 992382386864.dkr.ecr.us-east-1.amazonaws.com/user:500
        ports:
        - containerPort: 8080
        #livenessProbe
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        #Readiness probe
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        envFrom: 
          - configMapRef: 
              name: user-cm
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-cm
data:
  MONGO_URL: "mongodb://admin1:RoboShop1@roboshop-dev-docdb.cluster-cx6oecuq678h.us-east-1.docdb.amazonaws.com:27017/user?tls=true&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false"
  REDIS_HOST: "roboshop-dev-redis.fil0fy.0001.use1.cache.amazonaws.com"
---
#NodePort service
apiVersion: v1
kind: Service
metadata:
  name: user-svc
spec:
  selector:
    app: user
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
#HPA
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: user-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70